image:
  file: Dockerfile
checkoutLocation: "shopware"
ports:
  - port: 8000
    onOpen: open-preview
  - port: 3306
    onOpen: ignore
tasks:
  - name: Start Apache
    command: >
        apachectl start;
  - name: Start MySQL
    command: >
        mysqld --initialize-insecure;
        mysqld &
        sleep 5;
        echo "ALTER USER 'root'@'localhost' IDENTIFIED BY 'gitpod'; CREATE DATABASE shopware;" | mysql -uroot;
  - name: Shopware 6
    command: >
        cd $GITPOD_REPO_ROOT;
        cd src;
        composer install;
        mkdir -p var/log;
        mkdir -p var/cache;
        php public/recovery/install/index.php \
          --db-user=root \
          --db-password=gitpod \
          --db-name=shopware \
          --shop-locale=de-DE \
          --shop-name=Demoshop \
          --shop-email=demo@codeblick.de \
          --shop-currency=EUR \
          --shop-country=DEU \
          --admin-username=admin \
          --admin-firstname=John \
          --admin-lastname=Doe \
          --admin-password=shopware \
          --admin-email=demo@codeblick.de \
          --admin-locale=de-DE \
          --no-interaction \
          --no-skip-import;
        sed -i -r 's/APP_ENV=.+/APP_ENV=dev/g' .env;
        export APP_URL=$(gp url 8000);
        sed -i -r "s|APP_URL=.+|APP_URL=$APP_URL|g" .env;
        bin/console assets:install;
